name: CICD with docker

on:
 push:
  branches: [master]

jobs:
 build-deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install python
     uses: actions/setup-python@v4
     with: 
      python-version: "3.10"
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

