name: This is an experiment

on:
 push:
  branches: [master,main]
 pull_request:
  branches: [master,main]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install python
     uses: actions/setup-python@v4
     with: 
      python-version: "3.10"
   - name: Run python script
     run: python main.py
     env: 
      AGE: 100
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install python
     uses: actions/setup-python@v4
     with: 
      python-version: "3.10"
   - name: Run and test python script
     run: python main.py |
          python test.py
     env: 
      AGE: 100
      